### ISSUE TITLE
iOS does not receive push notifications in the foreground

### ISSUE THREAD

**Issue by konrad-thoc** [mirzemehdi/KMPNotifier#115]
I do not get push notifications when the app is in foreground mode. Why is this happening, on Android it works fine. I only get a notification when the app is in background. My setup on iOS. 

```
class AppDelegate: NSObject, UIApplicationDelegate {

  func application(_ application: UIApplication,
                   didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {

      FirebaseApp.configure()
      NotifierManager.shared.initialize(configuration: NotificationPlatformConfigurationIos(
        showPushNotification: true,
        askNotificationPermissionOnStart: false,
        notificationSoundName: "default"
      ))
      
    return true
  }

  func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        Messaging.messaging().apnsToken = deviceToken
  }
}
```

Should I handle it myself? Or should this happen automatically. I would also like to add that I send a push using a post with bellow json body:

```
{
  "message": {
    "topic": "news",
    "notification": {
      "title": "Breaking News",
      "body": "New news story available."
    },
    "apns": {
      "payload": {
        "aps": {
          "sound": "default"
        }
      }
    }
  }
}
```

**Comment by kotlin-compose-multiplatform** [comment]
same problem

**Comment by kotlin-compose-multiplatform** [comment]
Only called this method:

```
public fun NotifierManager.onApplicationDidReceiveRemoteNotification(userInfo: Map<Any?, *>) {
    val payloadData = userInfo.asPayloadData()
    if (payloadData.containsKey(KEY_IOS_FIREBASE_NOTIFICATION))
        NotifierManagerImpl.onPushPayloadData(payloadData)
}

```

**Comment by kotlin-compose-multiplatform** [comment]
@mirzemehdi

**Comment by kotlin-compose-multiplatform** [comment]
I fixed with this solution, bu not best way: 

```kotlin
import com.mmk.kmpnotifier.notification.NotifierManager
import com.mmk.kmpnotifier.notification.PayloadData
import kotlin.random.Random


object AppInitializer {
    fun onApplicationStart() {
        onApplicationStartPlatformSpecific()

        NotifierManager.addListener(object : NotifierManager.Listener {
            override fun onNewToken(token: String) {
                println("Push Notification onNewToken: $token")
            }

            override fun onPushNotification(title: String?, body: String?) {
                super.onPushNotification(title, body)
                println("Push Notification notification type message is received: Title: $title and Body: $body")
            }

            override fun onPayloadData(data: PayloadData) {
                super.onPayloadData(data)
                println("Push Notification payloadData: $data")
                val title = (data["aps"] as? Map<*, *>)?.get("alert")
                    ?.let { it as? Map<*, *> }
                    ?.get("title") as? String

                val body = (data["aps"] as? Map<*, *>)?.get("alert")
                    ?.let { it as? Map<*, *> }
                    ?.get("body") as? String

                val type = data["type"] as? String
                val id = data["id"] as? String
                val externalUrl = data["externalUrl"] as? String
                NotifierManager.getLocalNotifier().notify(
                    id = Random.nextInt(),
                    title = title?:"",
                    body = body?:"",
                    payloadData = mapOf(
                        "type" to type.toString(),
                        "id" to id.toString(),
                        "externalUrl" to externalUrl.toString()
                    )
                )
            }

            override fun onNotificationClicked(data: PayloadData) {
                super.onNotificationClicked(data)
                println("Notification clicked, Notification payloadData: $data")
            }
        })
    }
}
```

**Comment by konrad-thoc** [comment]
@kotlin-compose-multiplatform  ok I will try and let you know

**Comment by dominiram** [comment]
I've got the same issue and I've "fixed" it by adding `Messaging.messaging().subscribe(toTopic: "news")` to iOSApp.swift

**Comment by dominiram** [comment]
@kotlin-compose-multiplatform your solution works but I'm also receiving two notifications when the app is in background, do you have any ideas how to fix that?

**Comment by dominiram** [comment]
in the end I've fixed it by adding the native iOS code for receiving push notifications, since iOS has got some weird logic regarding push notifications while app is in foreground, if you guys want me to share it with you, ping me and I'll share it here

**Comment by rflash95** [comment]
@dominiram That’s awesome! Please drop the code here

**Comment by dominiram** [comment]
Sorry to keep you waiting guys, I was away for a few days, here's the code (THIS SHOULD BE INSERTED INSIDE iOSApp.Swift file):
first of all you should add `UNUserNotificationCenterDelegate` to you AppDelegate like this: `class AppDelegate: NSObject, UIApplicationDelegate, UNUserNotificationCenterDelegate`, second you should add `func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
          completionHandler([.alert, .badge, .sound])
      }` and also if you want to receive push notifications for topic, add this as well: `func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
        UNUserNotificationCenter.current().delegate = self
        Messaging.messaging().apnsToken = deviceToken
        Messaging.messaging().subscribe(toTopic: "news")
  }`

**Comment by mirzemehdi** [comment]
This issue is solved in https://github.com/mirzemehdi/KMPNotifier/pull/125. Please, reopen issue if it is still issue. This should be fixed in `1.5.0` version of the library

**Comment by LucasPrioste92** [comment]
Hi, I’m still not receiving the notification on the UI when the app is in the foreground on iOS, though the listener is called. Should I handle this manually and trigger a local notification when the app is in the foreground?
